swagger: "2.0"
info:
  title: Sample API
  description: Lab 1 API.
  version: 1.0.0
host: 127.0.0.1:5000/v1
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Get a full list of application users.
      produces:
        - application/json
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
          description: OK


    post:
      summary: Creating a new user.
      consumes:
        - application/json
#      description: Add a user to the database.
      parameters:
        - in: body
          name: user
          description: User to create
          schema:
            type: object
            $ref: '#/definitions/User'
      responses:
        201:
          description: Create


definitions:
  User:
    type: object
    required:
      - first_name
      - last_name
      - email
    properties:
      first_name:
        type: string
        example: "John"
      last_name:
        type: string
        example: "Smith"
      email:
        type: string
        example: "JohnSmith@mail.com"